#!/bin/bash

xset s noblank
xset s off
xset -dpms

nohup python3 -m http.server --directory /home/pi/pi-clock/ --bind 127.0.0.1 8080 &

# Tricking Chrome to think it exited cleanly
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'
sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences
c

unclutter -idle 5

/usr/bin/chromium-browser --incognito --noerrdialogs --disable-infobars --kiosk file:///home/pi/pi-clock/index.html

